language: node_js
nodejs:
  - stable
branches:
  only:
    - develop
env:
  global:
    - REMOTE_PATH=/var/www/raivencorps.me/Randy-FrontEnd
    - REMOTE_USER=travis
    - REMOTE_HOST=raivencorps.me
before_install:
  - bash scripts/install.sh
after_success:
  - bash scripts/deploy.sh
