type SeccionOptions = {
  TO_DO: 'TO DO|';
  GENERAL: 'GENERAL|',
  BILLS: 'BILLS|',
  SETTINGS: 'SETTINGS|',
  DASHBOARD: 'DASHBOARD|',
  CALENDAR: 'CALENDAR|'
};

export const SECCTION: SeccionOptions = {
  TO_DO: "TO DO|",
  GENERAL: 'GENERAL|',
  BILLS: 'BILLS|',
  SETTINGS: 'SETTINGS|',
  DASHBOARD: 'DASHBOARD|',
  CALENDAR: 'CALENDAR|'
}
